# Generated by Django 5.0.1 on 2024-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PagePasteBin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_password",
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
